sonar.projectKey=caaiobomfim_app-go-continuous-integration-sonarcloud
sonar.organization=caaiobomfim

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out